In [2]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


In [3]:
import tensorflow as tf

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout



In [5]:
import pandas as pd
import numpy as np


In [7]:
data = pd.read_csv("Credit.csv")

In [8]:
data 

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4521 rows x 9 columns]

In [9]:
data['job'].unique()    

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown', nan], dtype=object)

In [10]:
job = {'admin.':0,'blue-collar':1,'entrepreneur':2,'housemaid':3,'management':4,'retired':5,'self-employed':6,'services':7,'student':8,'technician':9,'unemployed':10,'unknown':11}
data['job'] = data['job'].map(job)
data['marital'] = data['marital'].map({'married':0,'single':1,'divorced':2})
data['education'] = data['education'].map({'primary':0,'secondary':1,'tertiary':2})
data['housing'] = data['housing'].map({'yes':0,'no':1})
data['approval'] = data['approval'].map({'yes':0,'no':1})

In [12]:
data.drop_duplicates(inplace=True)

In [13]:
data.dropna(inplace=True)

In [14]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [16]:
x =data.drop('approval',axis=1)
y = data['approval']

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [18]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3452, 8), (863, 8), (3452,), (863,))

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [24]:
input_dim=8

In [25]:
model =Sequential()
# input layer
model.add(Dense(units=128,activation='relu',input_dim=input_dim))
# Dropout layer 
model.add(Dropout(0.2))
# Hidden layer

model.add(Dense(units = 64,activation='relu'))
model.add(Dense(units = 32,activation='relu'))
model.add(Dense(units = 16,activation='relu'))
model.add(Dense(units = 8,activation='relu'))
# output layer


model.add(Dense(units=1,activation='sigmoid'))


model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy','mae','mse'])

In [ ]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7810 - loss: 39.1052 - mae: 0.2426 - mse: 0.1993
Epoch 2/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7739 - loss: 4.8537 - mae: 0.2750 - mse: 0.1905
Epoch 3/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8332 - loss: 335.5934 - mae: 0.2207 - mse: 0.1523
Epoch 4/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8214 - loss: 7.0199 - mae: 0.2572 - mse: 0.1556
Epoch 5/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 3.1778 - mae: 0.1502 - mse: 0.1335
Epoch 6/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8322 - loss: 1.0589 - mae: 0.2368 - mse: 0.1402
Epoch 7/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8677 - loss: 0.6016 - mae: 0.2181 - mse: 0.1181
Epoch 8/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8728 - loss: 17.3275 - mae: 0.2431 - mse: 0.1179
Epoch 9/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8836 - loss: 4.003

In [38]:
pred = model.predict(x_test)

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [ ]:
# pred =pd.DataFrame(pred)

In [41]:
import numpy

In [42]:
pred =numpy.ravel(pred)

In [43]:
pred

array([0.78848433, 0.76334643, 0.93692493, 0.9300364 , 0.8047085 ,
       0.7682355 , 0.94811153, 0.7732578 , 0.98271024, 0.7655461 ,
       0.9617871 , 0.77125007, 0.7506267 , 0.7857032 , 0.78371   ,
       0.8427673 , 0.78390783, 0.9580059 , 0.75058264, 0.7992075 ,
       0.99481463, 0.8818426 , 0.7599187 , 0.8017589 , 0.7642213 ,
       0.9692727 , 0.7491603 , 0.8576589 , 0.8032597 , 0.95339745,
       0.9935326 , 0.99995863, 0.9293373 , 0.90110505, 0.9184758 ,
       0.76606166, 0.76330364, 0.96251494, 0.7802191 , 0.8392817 ,
       0.9741123 , 0.79941696, 0.88220054, 0.75953674, 0.75738   ,
       0.9506384 , 0.8379731 , 0.71867007, 0.90966415, 0.90364367,
       0.8713271 , 0.9980013 , 0.87933266, 0.83400285, 0.76643956,
       0.9999999 , 0.84944797, 0.8441232 , 0.7922509 , 0.75133884,
       0.99739295, 0.7980373 , 0.749851  , 0.7755352 , 0.97051334,
       0.7803782 , 0.76800925, 0.76281416, 0.77702117, 0.96310264,
       0.7616021 , 0.937807  , 0.9714253 , 0.77194476, 0.80732

In [37]:
y_test

997     1
309     1
3865    1
1678    1
1125    1
       ..
2805    1
134     1
3851    1
1597    1
1074    1
Name: approval, Length: 863, dtype: int64

In [48]:
output =pd.DataFrame({'actual':y_test,'prediction':(pred>=0.5).astype(int)})

In [51]:
output['prediction'].unique()

array([1])

In [52]:
output['actual'].unique()

array([1, 0], dtype=int64)

In [ ]:
# balancing 