In [1]:
!pip install numpy

DEPRECATION: Loading egg at c:\users\kumaw\appdata\local\programs\python\python313\lib\site-packages\healthcare-0.0.2-py3.13.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\kumaw\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
print("successfully installed")

successfully installed


In [3]:
print("numpy version:-",np.__version__) 


numpy version:- 1.26.4


In [ ]:
# Array and list  

# Array similar data store krta hai hain
# array >>>>>>>[1,2,3,4,5,6,7,8,9] 

# list >>>>>>[1,2,3,4,5,6,7,8,9, "ritik", 2.5, True, [1,2,3]]

##### list convert into array 

In [8]:
# lst = [1,2,3,4,5]
# print("type of list:-",type(lst))
# arr =np.array(lst)
# print(arr)
# print("type of array:-",type(arr))

In [9]:
arrr =np.array([1,2,3,4,5])

In [10]:
print(arrr)
print("type of array:-",type(arrr))

[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [ ]:
lst = list(range(1, 20)) # list function is used to create list and range function is used to create range

In [14]:
type(lst)
arr =np.array(lst)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr =np.arange(1,20) #arange function is used to create array 
type(arr)

numpy.ndarray

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [20]:
arr =np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr =np.zeros((5,10))  # 5 rows and 10 columns and zero is used to create array
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.ones((5,10)) # one is used to create array
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.linspace(1,10,5) # linspace function is used to create array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

##### 1D array convert into 2D

In [29]:
arr=np.arange(0,30) # arange function is used to create array

In [32]:
arr.reshape(5,6) # reshape function is used to create array   

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [35]:
arr=np.random.randint(1,5,9) # random function is used to create array
arr

array([4, 3, 2, 2, 4, 2, 3, 3, 2])

In [36]:
arr=np.random.randint(1,5,(5,2)) # random function is used to create array
arr

array([[3, 4],
       [3, 4],
       [2, 2],
       [3, 1],
       [4, 1]])

In [38]:
arr=np.random.random(10) # seed function is used to create array
arr

array([0.3554114 , 0.19134654, 0.28425397, 0.00663987, 0.67280403,
       0.76326652, 0.29542287, 0.58081712, 0.40536715, 0.95710556])

In [39]:
arr=np.random.random((5,10)) # seed function is used to create array
arr

array([[0.63226299, 0.40907501, 0.43748353, 0.98589678, 0.07252596,
        0.61977802, 0.78911032, 0.41157577, 0.39848119, 0.23566705],
       [0.32375108, 0.87570257, 0.62521455, 0.09720308, 0.77437727,
        0.87547786, 0.30003809, 0.5798339 , 0.17381009, 0.67243072],
       [0.14615453, 0.03861014, 0.19744263, 0.53688885, 0.92137217,
        0.1619965 , 0.11979893, 0.45490818, 0.26564049, 0.54343336],
       [0.77073635, 0.94753558, 0.65835209, 0.21208488, 0.43891062,
        0.37216166, 0.82942148, 0.45406385, 0.60982649, 0.00675663],
       [0.20767059, 0.65109044, 0.15171269, 0.71648986, 0.03183853,
        0.18808061, 0.41720046, 0.2120465 , 0.26677878, 0.72278982]])

In [40]:

arr =np.arange(60).reshape(12,5) # seed function is used to create array

In [47]:
print("array shape :-",arr.shape)
print("array size:-",arr.size)
print("array data type:-",arr.dtype)
print("array dimension:-",arr.ndim)

array shape :- (12, 5)
array size:- 60
array data type:- int32
array dimension:- 2


In [49]:
arr.flatten() ##  2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [50]:
arr.ravel() # 2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [55]:
arr.shape

(12, 5)

In [58]:
arr.T.shape

(5, 12)

In [69]:
# 1D 
arr =np.arange(30)
arr[0]

0

In [70]:
# 1D 
arr =np.arange(30)
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr =np.arange(30)
arr[0]=100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [76]:
# 2 D 
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [77]:
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


6

In [79]:
arr[1,3:5]

array([8, 9])

In [ ]:
arr[0:5,1:2]   # row (o:5 means 0 to 4), column 

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [82]:
arr[7:8,4][0]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [83]:
arr[11,4]

59

In [84]:
arr[-1,-1]

59

In [85]:
arr[-1][-1]

59

In [86]:
arr[11][-1]

59

In [87]:
# 3d array

In [ ]:
arr =np.array(np.arange(225).reshape(5,15,3))
arr.ndim, arr.shape, arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int32'))

In [92]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [91]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [93]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [94]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [99]:
arr[2][3][1]=200
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 200, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [103]:
arr =np.array([3,2,1,5,4])

In [104]:
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr+2

array([3, 4, 5, 6, 7])

In [106]:
arr*2

array([ 2,  4,  6,  8, 10])

In [107]:
arr-1

array([0, 1, 2, 3, 4])

In [108]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [109]:
arr =np.array([3,2,1,5,4])
arr1 =np.array([3,2,1,5,4])
arr+arr1

array([ 6,  4,  2, 10,  8])

In [1]:
💖💖💖💖💖💖💖
💖 I       💖
💖   LOVE 💖
💖     YOU 💖
💖💖💖💖💖💖💖


SyntaxError: invalid character '💖' (U+1F496) (2249304393.py, line 1)

In [2]:
import time

def type_print(text, delay=0.1):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

# Romantic message using emojis
message = """
💖💖💖💖💖💖💖💖💖
💖 I Love You So Much 💖
💖     Forever Yours     💖
💖     ❤️ My Queen ❤️     💖
💖💖💖💖💖💖💖💖💖
"""

# Heart animation
hearts = ["❤️", "💖", "💕", "💘", "💞", "💗", "💓", "💝"]

def show_love():
    for heart in hearts:
        print(f"I love you {heart}")
        time.sleep(0.5)

# Run the romantic script
type_print(message, 0.05)
show_love()
type_print("💍 Will you be mine forever? 💌", 0.07)



💖💖💖💖💖💖💖💖💖
💖 I Love You So Much 💖
💖     Forever Yours     💖
💖     ❤️ My Queen ❤️     💖
💖💖💖💖💖💖💖💖💖

I love you ❤️
I love you 💖
I love you 💕
I love you 💘
I love you 💞
I love you 💗
I love you 💓
I love you 💝
💍 Will you be mine forever? 💌


In [4]:
import time
import os

# Function to simulate typing effect
print("Nishu(Meri lugaii) love you")
def type_print(text, delay=0.07):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

# Clear screen for better effect
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

# Animated heart frames
heart_frames = [
    "   💖     💖\n     💖 💖\n       💖",
    "   💕     💕\n     💕 💕\n       💕",
    "   💘     💘\n     💘 💘\n       💘",
    "   💓     💓\n     💓 💓\n       💓"
]

# Romantic message
message = """
💌💌💌 MESSAGE FOR YOU 💌💌💌

My dearest love 💕,

Every moment with you feels magical ✨.
Your smile lights up my world 🌍,
And your heart is where I want to live forever 🏡❤️.

You are my sunshine ☀️, my moon 🌙, my everything 💫.

"""

proposal = "💍 Will you make me the happiest person alive and be mine forever? 💖"

# Show animated hearts
def show_animated_hearts(repeat=2):
    for _ in range(repeat):
        for frame in heart_frames:
            clear_screen()
            print(frame)
            time.sleep(0.3)

# Run the love script
clear_screen()
type_print(message)
time.sleep(1)
show_animated_hearts()
type_print(proposal)


Nishu(Meri lugaii) love you

💌💌💌 MESSAGE FOR YOU 💌💌💌

My dearest love 💕,

Every moment with you feels magical ✨.
Your smile lights up my world 🌍,
And your heart is where I want to live forever 🏡❤️.

You are my sunshine ☀️, my moon 🌙, my everything 💫.


   💖     💖
     💖 💖
       💖
   💕     💕
     💕 💕
       💕
   💘     💘
     💘 💘
       💘
   💓     💓
     💓 💓
       💓
   💖     💖
     💖 💖
       💖
   💕     💕
     💕 💕
       💕
   💘     💘
     💘 💘
       💘
   💓     💓
     💓 💓
       💓
💍 Will you make me the happiest person alive and be mine forever? 💖


In [5]:
import time

def type_print(text, delay=0.07):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

message = """
💖 To My Love: Nishu 💖

You make my world brighter 🌟,
My heart happier ❤️,
And my life complete 💫.

I 💘 you, Nishu — forever & always! 💍
"""

type_print(message)



💖 To My Love: Nishu 💖

You make my world brighter 🌟,
My heart happier ❤️,
And my life complete 💫.

I 💘 you, Nishu — forever & always! 💍



In [7]:
import time
import os

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

# Love message styles
messages = [

    # Style 1: Classic Box
    """
    💖💖💖💖💖💖💖
    💖 I 💘 U 💖
    💖 NISHU 💖
    💖💖💖💖💖💖💖
    """,

    # Style 2: Romantic Letter
    """
    🌹 To: Nishu 🌹

    I 💖 you more every day.
    You're my 🌞 sunshine, my 🌙 moonlight,
    My forever and always 💍

    Yours truly,
    💌 Your Love
    """,

    # Style 3: Heart Art
    """
      💕     💕
     💕 💕 💕 💕
    💕   💕 💕   💕
     💕       💕
       💕   💕
         💕
       NISHU 💖
         I ❤️ YOU
    """,

    # Style 4: Python Style
    """
    def love_message(name):
        return f"I ❤️ you forever, {name}! 💍💖"

    print(love_message("Nishu"))
    """,

    # Style 5: Starry Dream
    """
    🌟🌙 Dear Nishu 🌙🌟

    You light up my world ✨
    You fill my heart with joy 💞
    And I can't stop loving you 💘

    💍 Be mine forever?
    """
]

# Show each message with animation
for msg in messages:
    clear()
    print(msg)
    time.sleep(3)  # Wait before next style

clear()
print("💖 Thank you for watching this love show, Nishu! 💖")




    💖💖💖💖💖💖💖
    💖 I 💘 U 💖
    💖 NISHU 💖
    💖💖💖💖💖💖💖
    

    🌹 To: Nishu 🌹

    I 💖 you more every day.
    You're my 🌞 sunshine, my 🌙 moonlight,
    My forever and always 💍

    Yours truly,
    💌 Your Love
    

      💕     💕
     💕 💕 💕 💕
    💕   💕 💕   💕
     💕       💕
       💕   💕
         💕
       NISHU 💖
         I ❤️ YOU
    

    def love_message(name):
        return f"I ❤️ you forever, {name}! 💍💖"

    print(love_message("Nishu"))
    

    🌟🌙 Dear Nishu 🌙🌟

    You light up my world ✨
    You fill my heart with joy 💞
    And I can't stop loving you 💘

    💍 Be mine forever?
    
💖 Thank you for watching this love show, Nishu! 💖


In [1]:
!pip install moviepy


In [2]:
from moviepy.editor import TextClip, concatenate_videoclips

messages = [
    "💖 I 💘 U 💖\n💖 NISHU 💖",
    "You're my 🌞, my 🌙, my 💍",
    "💕     💕\n 💕 NISHU 💖 💕\n   I ❤️ YOU",
    "I ❤️ you forever, Nishu! 💍💖",
    "You light up my world ✨\nBe mine forever? 💘"
]

clips = []
for msg in messages:
    clip = TextClip(msg, fontsize=48, color='red', size=(600, 400), method='caption', font='DejaVu-Sans')
    clip = clip.set_duration(2)
    clips.append(clip)

final_clip = concatenate_videoclips(clips, method="compose")
final_clip.write_gif("nishu_love.gif", fps=10)


ModuleNotFoundError: No module named 'moviepy.editor'